export const SHADES = [
  {
    id: 'scarlet',
    no: '01',
    name: 'Scarlet',
    bullet: '#d7263d',
    accent: '#e0344b',
    tint: 'rgba(215, 38, 61, 0.16)',
    finish: 'Velvet matte',
    line: 'The signature. A blue-red that flatters every undertone.',
    img: '/media/shade_scarlet.jpg',
  },
  {
    id: 'bare',
    no: '02',
    name: 'Bare',
    bullet: '#c99b82',
    accent: '#d9ae8c',
    tint: 'rgba(201, 155, 130, 0.14)',
    finish: 'Silk satin',
    line: 'Nude with a pulse. Skin, but better.',
    img: '/media/shade_bare.jpg',
  },
  {
    id: 'berry',
    no: '03',
    name: 'Berry',
    bullet: '#7a2048',
    accent: '#93335c',
    tint: 'rgba(122, 32, 72, 0.18)',
    finish: 'Velvet matte',
    line: 'Plum depth, poured after dark.',
    img: '/media/shade_berry.jpg',
  },
  {
    id: 'coral',
    no: '04',
    name: 'Coral',
    bullet: '#ed6a5a',
    accent: '#f27a66',
    tint: 'rgba(237, 106, 90, 0.14)',
    finish: 'Silk satin',
    line: 'Sun-struck. A warm flare of orange-pink.',
    img: '/media/shade_coral.jpg',
  },
]
